name: Test peuler

on:
  workflow_run:
    workflows: [Test pmath]
    types: [completed]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test peuler on ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./peuler

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Build
        run: cargo build --all-features

      - name: Test
        run: cargo test --all-features

      - name: Docs
        run: cargo doc --all-features

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all --check
