[package]
name = "web"
version = "0.1.0"
description = "Web frontend for peuler"
edition = "2024"
publish = false

[dependencies]
js-sys = "0.3.105"
peuler = { path = "../peuler" }
pmath = { path = "../pmath" }
wasm-bindgen = "0.2.128"

[lib]
name = "web"
crate-type = ["cdylib"]
path = "src/lib.rs"
